version: '3'

services:
  web:
    build: .
    command: sh -c "chmod +x ./build.sh && ./build.sh && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - TZ=UTC 
