# Generated by Django 5.0.2 on 2024-04-06 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Tengri", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="article",
            name="main_link",
        ),
        migrations.RemoveField(
            model_name="article",
            name="main_text",
        ),
        migrations.RemoveField(
            model_name="article",
            name="project_date",
        ),
        migrations.RemoveField(
            model_name="article",
            name="project_logo",
        ),
        migrations.RemoveField(
            model_name="article",
            name="project_tags",
        ),
        migrations.RemoveField(
            model_name="article",
            name="title",
        ),
    ]
