# Generated by Django 5.0.2 on 2024-04-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tengri", "0002_remove_article_authors_remove_article_main_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="main_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="main_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="project_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="project_logo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="project_tags",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title",
            field=models.CharField(default="No title", max_length=200),
        ),
    ]
