# Generated by Django 5.0.2 on 2024-04-07 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Tengri", "0003_article_authors_article_main_link_article_main_text_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
    ]
