# Generated by Django 5.0.2 on 2024-04-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Tengri", "0004_delete_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "project_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(default="No title", max_length=200)),
                ("authors", models.CharField(blank=True, max_length=200, null=True)),
                ("main_text", models.TextField(blank=True, null=True)),
                ("main_link", models.CharField(max_length=200)),
                ("project_date", models.DateTimeField(blank=True, null=True)),
                (
                    "project_logo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("project_tags", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
